name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    
    - name: Restore
      run: dotnet restore netconf
    
    - name: Build with dotnet
      run: dotnet build netconf --configuration Release


    - name: Dotnet Publish
      run: dotnet publish netconf --configuration Release -o netcore 
      
    - uses: azure/webapps-deploy@v1
      with: 
        app-name: netconfsjc
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: '${GITHUB_WORKSPACE}/VSSUMMIT/vssummit/' 
